spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: arqonia2
      username: arqoniaMongoUser
      password: "{cipher}7fccbb5653090fede3d930f842a33667d9303a9b20eed6f17d4d40465e773ccf389aa6c1d40f5f51b2ef19f1ca5d6744"
#      password: arqoniaSuperPass12
