spring:
  data:
    mongodb:
      database: arqonia2
      port: 27017
      uri: mongodb://localhost
  profiles:
    active: local

#server:
#  ssl:
#    enabled: true # set to FALSE, if want to disable HTTPS and switch back to HTTP
#    key-store-type: JKS
#    key-store: classpath:keystore/https.prod/arqonia_https.jks
#    key-store-password: pass123
#    key-alias: arqonia_https
#    trust-store: classpath:keystore/https.prod/arqonia_https.jks
#    trust-store-password: pass123

server:
  ssl:
    enabled: true # set to FALSE, if want to disable HTTPS and switch back to HTTP
    key-store-type: JKS
    key-store: classpath:keystore/https.try/arqonia_https.jks
    key-store-password: pass123
    key-alias: arqonia_https
  port: 8443

#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"

#ONLY FOR DEVELOPMENT AND TESTING !
#logging:
#  level:
#     pl.astronomy.arqonia20: DEBUG
#     ROOT: DEBUG

arqonia:
  admin:
    username: abekalarz

