spring:
  data:
    mongodb:
      database: arqonia2
      port: 27017
      uri: mongodb://localhost
      password: password

server:
  ssl:
    enabled: true # set to FALSE, if want to disable HTTPS and switch back to HTTP
    key-store-type: JKS
    key-store: classpath:keystore/https/integration/server/server.jks
    key-store-password: secret
    key-password: secret
    key-alias: localhost

arqonia:
  admin:
    password: password
