spring:
  data:
    mongodb:
      database: arqonia2
      port: 27017
      uri: mongodb://localhost
  profiles:
    active: local

server:
  ssl:
    enabled: true # set to FALSE, if want to disable HTTPS and switch back to HTTP
    key-store-type: JKS
    key-store: classpath:keystore/https.try2/server/server.jks
    key-store-password: secret
    key-password: secret
    key-alias: localhost
  port: 8443

simbadClient:
  url: http://simbad.u-strasbg.fr/simbad/sim-tap/sync
  connectionTimeout: 300
  socketTimeout: 300
  query: SELECT id2.id FROM ident AS id1 JOIN ident AS id2 USING(oidref) WHERE id1.id = '%s';

vizierClient:
  url: http://tapvizier.u-strasbg.fr/TAPVizieR/tap/view
  connectionTimeout: 300
  socketTimeout: 300
  query: test;

vizier-queries:
  queries:
    SAO: SELECT TOP 100 * FROM "I/131A/sao" WHERE recno = '%s';
    HIP: SELECT TOP 100 * FROM "I/239/hip_main" WHERE recno = '%s';
    TYC: SELECT TOP 100 * FROM "I/239/tyc_main" where "I/239/tyc_main".TYC = '%s';
    HD: SELECT TOP 100 * FROM "III/135A/catalog" WHERE recno = '%s';
    HR: SELECT TOP 100 * FROM "V/50/catalog" WHERE recno = '%s';
    GC: SELECT TOP 100 * FROM "I/113A/catalog" WHERE recno = '%s';

selectedCatalogs:
  startingNames: SAO, HIP, TYC, HD, HR, GC


#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"

#ONLY FOR DEVELOPMENT AND TESTING !
#logging:
#  level:
#     pl.astronomy.arqonia20: DEBUG
#     ROOT: DEBUG

arqonia:
  admin:
    username: abekalarz

