#spring:
#  data:
#    mongodb:
#      database: arqonia2
#      port: 27017
#      uri: mongodb://mongo

spring:
  data:
    mongodb:
      host: mongo
      port: 27017
      database: arqonia2
      username: arqoniaMongoUser
      password: arqoniaSuperPass12

arqonia:
  admin:
    username: abekalarz
