spring:
  data:
    mongodb:
      database: arqonia2
      port: 27017
      uri: mongodb://localhost
      password: password

arqonia:
  admin:
    password: password

server:
  ssl:
    enabled: true # set to FALSE, if want to disable HTTPS and switch back to HTTP
    key-store-type: PKCS12
    key-store: classpath:keystore/https/dev/keystore.p12
    key-store-password: password
    key-password: password
    key-alias: tomcat

#server:
#  ssl:
#    enabled: true # set to FALSE, if want to disable HTTPS and switch back to HTTP
#    key-store-type: JKS
#    key-store: classpath:keystore/https/integration/server/server.jks
#    key-store-password: secret
#    key-password: secret
#    key-alias: localhost
