spring:
  data:
    mongodb:
      database: arqonia2
      port: 27017
      uri: mongodb://localhost
  profiles:
    active: local



#TODO Remove after 'full OAUth2 implementation'!
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"

#ONLY FOR DEVELOPMENT AND TESTING !
#logging:
#  level:
#     pl.astronomy.arqonia20: DEBUG
#     ROOT: DEBUG

arqonia:
  admin:
    username: abekalarz
