spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: arqonia2
      username: arqoniaMongoUser
      password: "{cipher}4ffa699e0a2f174d483760975b1ce3161f57a8defa6dbc641bd48c64b0722b47f9a39507137505b7754413a970cc0bd3"
  profiles:
    active: local
  main:
    allow-bean-definition-overriding: true
  resources:
    cache:
      cachecontrol:
        max-age: 14400
        cache-private: true
        must-revalidate: true

server:
  ssl:
    enabled: true # set to FALSE, if want to disable HTTPS and switch back to HTTP
    key-store-type: PKCS12
    key-store: classpath:keystore/https/prod/keystore.p12
    key-store-password:
    key-password:
    key-alias: tomcat
  port: 443
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1KB

simbadClient:
  url: http://simbad.u-strasbg.fr/simbad/sim-tap/sync
  connectionTimeout: 300
  socketTimeout: 300
  query: SELECT id2.id FROM ident AS id1 JOIN ident AS id2 USING(oidref) WHERE id1.id = '%s';

vizierClient:
  url: http://tapvizier.u-strasbg.fr/TAPVizieR/tap/view
  connectionTimeout: 1000
  socketTimeout: 500
  retryCount: 3

vizier-queries:
  queries:
    SAO:
      SELECT TOP 100 recno AS object_name, vmag AS "V", sptype AS spectral_type
      FROM "I/131A/sao"
      WHERE recno = '%s';
    HIP:
      SELECT TOP 100 recno AS object_name, vmag AS "V", "B-V" + vmag as "B", "B-V" AS "B-V",
        "V-I" AS "V-I", sptype AS spectral_type, rahms AS "RA", dedms AS "DE"
      FROM "I/239/hip_main"
      WHERE recno = '%s';
    TYC:
      SELECT TOP 100 tyc AS object_name, vmag AS "V", "B-V" + vmag as "B", "B-V" AS "B-V",
        rahms AS "RA", dedms AS "DE"
      FROM "I/239/tyc_main"
      WHERE "I/239/tyc_main".TYC = '%s';
    HD:
      SELECT TOP 100 recno AS object_name, spt AS spectral_type
      FROM "III/135A/catalog"
      WHERE recno = '%s';
    HR:
      SELECT TOP 100 recno AS object_name, "U-B" + "B-V" + vmag AS "U", vmag AS "V",
        "B-V" + vmag AS "B", "B-V" AS "B-V", "U-B" AS "U-B", "R-I" AS "R-I", sptype AS spectral_type
      FROM "V/50/catalog"
      WHERE recno = '%s';
    GC:
      SELECT TOP 100 recno AS object_name, vmag AS "V", sptype AS spectral_type
      FROM "I/113A/catalog"
      WHERE recno = '%s';

arqonia:
  admin:
    username: abekalarz
    password: "{cipher}6db2597356ec55292cd52c96dbda9f545285f2c46690e96ba9d7ce5a67343fb229f3d6946c298ca08f9e4e80d9947c97"

#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"

#ONLY FOR DEVELOPMENT AND TESTING !
#logging:
#  level:
#     pl.astronomy.arqonia20: DEBUG
#     ROOT: DEBUG

