version: '3.1'

services:
  mongo:
    image: mongo:3.6
    ports:
      - 27017:27017
    volumes:
      - ../database_store/mongo:/data/db
    networks: 
      - spring-boot-network
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 30s
    healthcheck:
      test: ["CMD", "pgrep", "mongod"]
      interval: 5s
      timeout: 5s
      retries: 5

  mongo_import:
    image: mongo:3.6
    links:
      - mongo
    networks: 
      - spring-boot-network
    volumes:
      - ./mongo-import:/mongo-import
    command:
      /mongo-import/import.bat
    restart: on-failure
    depends_on:
      - mongo

  arqonia_build_and_run:
    image: arqonia_build_and_run
    build: .
    ports:
      - 8080:8080
    networks:
      - spring-boot-network
    depends_on:
      - mongo

networks:
  spring-boot-network:
    driver: bridge

#    When for example we have 'ports':
#    ports:
#      - 8081:8080
#    then '8081' is the host port and '8080' is the service port ('host port:service port')